# Generated by Django 4.0.10 on 2023-02-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DEL', 'Delegate'), ('CHA', 'Chair'), ('ADV', 'Advisor'), ('ADM', 'Admin')], default='Delegate', max_length=3),
        ),
    ]
