version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '5557:5555'
    depends_on:
      - redis