version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./compose/production/django/Dockerfile
    command: gunicorn vmun_backend.asgi:application -k uvicorn.workers.UvicornWorker --bind  0.0.0.0:8000 --access-logfile -
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env.prod
    ports:
      - '5557:5555'
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  nginx-proxy:
      container_name: nginx-proxy
      build: ./compose/production/nginx
      restart: always
      ports:
        - '443:443'
        - '80:80'
      volumes:
        - static_volume:/home/app/web/staticfiles
        - certs:/etc/nginx/certs
        - html:/usr/share/nginx/html
        - vhost:/etc/nginx/vhost.d
        - /var/run/docker.sock:/tmp/docker.sock:ro
      depends_on:
        - web

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  certs:
  html:
  vhost:
  acme: