version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    image: django_celery_example_web
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery_worker:
    container_name: vmun_backend-celery-worker
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  celery_beat:
    container_name: vmun_backend-celery-beat
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  flower:
    container_name: vmun_backend-celery-flower
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '5557:5555'
    depends_on:
      - redis