# Generated by Django 4.0.10 on 2023-02-28 00:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', unique=True)),
                ('venue', models.CharField(max_length=200)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.institution')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
