# Generated by Django 4.0.10 on 2023-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=10),
        ),
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=10),
        ),
    ]
